language: php

php:
 - 7.3

before_script:
 - phpenv config-rm xdebug.ini
 - echo | pecl install channel://pecl.php.net/yaml-2.1.0
 - git clone https://github.com/pmmp/pthreads.git
 - cd pthreads
 - git checkout 646dac62ae0d48c1ada7b007e15575fb84f7d71d
 - phpize
 - ./configure
 - make
 - make install
 - cd ..
 - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
 - php ./src/pocketmine/PocketMine.php --no-wizard --plugins="tests"

notifications:
 email: true
